### ISSUE TITLE
Need to use personal portapps.cfg. for Privacy setting.

### ISSUE THREAD

**Issue by tawusaw** [portapps/firefox-portable#4]
I need to use personal portapps.cfg. Can i config it by *.yml ? or need to mod main.go and recompile only? In my personal opinion you could separate modifier *.cfg (and other) section from main launcher for reduce launcher file size (a bit big compare to portableapps.com App) and lets user take control the privacy setting in portapps.cfg.

**Comment by crazy-max** [comment]
@tawusaw There is no `portapps.cfg`, only `portapps.yml` YAML file. See [Configuration page](https://portapps.io/doc/configuration/) for more info and read [Info section of Firefox portable page](https://portapps.io/app/firefox-portable/#infos).

**Comment by tawusaw** [comment]
I mean i need to modify portapps.cfg in firefox app but i can't because your app take control over it (As Pic).
![Capture](https://user-images.githubusercontent.com/27891725/60039173-51291b80-96e0-11e9-8301-829d2d4aa182.JPG)
 Please lets user take control the privacy setting in portapps.cfg. Thank you.

**Comment by crazy-max** [comment]
Oh ok sorry you mean `portapps.cfg` to update Firefox configuration. I come back to you when I have a solution.

**Comment by crazy-max** [comment]
@tawusaw You can already set your preferences in your profile through `data\profile\default\prefs.js`. Have you ever tried it?

**Comment by crazy-max** [comment]
I close this issue because `data\profile\default\prefs.js` can be used to set these preferences.
