### ISSUE TITLE
Cant change UI language in options either in amending the main YAML configuration file

### ISSUE THREAD

**Issue by vaallx** [portapps/firefox-portable#5]
I modified it with in this two way,but it did't work and rolled back to default setting.
Happends in vision 68.0
I tested vision 67.0 work succesfully

![image](https://user-images.githubusercontent.com/51045148/60941763-cc124900-a312-11e9-9d3b-9689e7f08672.png)

![image](https://user-images.githubusercontent.com/51045148/60941836-02e85f00-a313-11e9-803e-30c48612c501.png)

**Comment by crazy-max** [comment]
As explained on [Configuration](https://portapps.io/doc/configuration/) page, the sample file has to be renamed.

**Comment by crazy-max** [comment]
Also, do not use notepad to edit this file. Use something like Notepad++.
