### ISSUE TITLE
Starting Firefox portable when another Firefox (regular install) is running just opens firefox.exe

### ISSUE THREAD

**Issue by Forceflow** [portapps/firefox-portable#6]
Steps to reproduce:

1. Install Firefox from Mozilla (the default way)
2. Open a Firefox window
3. Install Portapps Firefox
4. Start firefox-portable

Observe how it just forks off another instance of the running firefox.exe.
I can only start firefox portable by closing all "regular" firefox instances.

It works the other way around too, by the way:

1. Open firefox-portable ->firefox portable window opens
2. Open mozilla-installed firefox.exe -> new firefox portable window opens

I've tried playing with the AllowMultipleInstances setting, but that does not change anything, unfortunately.

**Comment by crazy-max** [comment]
Hi @Forceflow, thanks for your report, I will take a look on this.

**Comment by Forceflow** [comment]
I think the process just checks for a running firefox.exe (regardless of origin), and requests a new window from that process. Renaming the executable probably fixes this.

**Comment by crazy-max** [comment]
@Forceflow That seems to be it, indeed. I'll try to find a way to get around this behavior.

**Comment by crazy-max** [comment]
@Forceflow Unfortunately I cannot reproduce your issue. Here is the scenario I realized:

* Install Firefox from Mozilla (FirefoxSetup-69.0.3-win64.exe)
* Install Firefox portable to `C:\portapps\firefox-portable` (firefox-portable-win64-69.0.2-26-setup.exe)
* Launch Mozilla Firefox
* Launch Firefox Portable

Everything works as expected. I've got 2 separated instances:

![image](https://user-images.githubusercontent.com/1951866/66675380-83e22a00-ec65-11e9-899f-dcc51f491946.png)

Tried the other way around too and it's ok for me. I've also tried to open a new window and everything is linked as expected.

Can you give me your Firefox (mozilla/portable) version and architecture (32/64). And also create a proper [bug report](https://github.com/portapps/firefox-portable/issues/new?template=bug_report.md) please? Thanks.
